
sudo: required

language: node_js

node_js:
    "8.11.1"

before_install:
    - npm i -g npm

install:
    - npm ci

cache:
    diretories:
        - "node_modules"

script:
    - npm run lint
    - npm run test
